language: csharp
solution: DotnetTestCI.sln
install:
  - nuget restore DotnetTestCI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DotnetTestCI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyProject.Tests/bin/Release/DotnetTestCI.Tests.dll
